Dockerfile
plast-lab/cclyzer-souffle pull request #10
Opened 2021-06-22 00:52 UTC by adrianherrera

Also added output directory option to cclyzer script, which makes it easier to use with mounted volumes in a Docker container.

2021-06-22 18:04 UTC, ktrianta requested changes
Thank you a lot for your pull request! I have created two small suggestions that should be addressed before merging.

2021-06-22 18:04 UTC, ktrianta commented on README.md
> +    apt install llvm libclang-dev
I created a separate commit for this. Can you please delete this change?

2021-06-22 18:04 UTC, ktrianta commented on cclyzer.sh
> +    echo Output direcctory "$OUTPUT_DIR" not found!
```suggestion
    echo Output directory "$OUTPUT_DIR" not found!
```

2021-06-22 18:04 UTC, ktrianta commented on README.md
> +    apt install llvm libclang-dev
```suggestion
    apt install llvm
```

2021-06-23 01:48 UTC, adrianherrera commented
Thanks @ktrianta! Changes have been made.

2021-06-23 05:38 UTC, ktrianta commented
Thank you!

2021-06-23 05:39 UTC, merged